BitPayConfiguration:
    Environment: null
    EnvConfig:
        Test:
            PrivateKeyPath: null
            PrivateKeySecret: null
            ApiTokens:
                merchant: null
                payroll: null
        Prod:
            Url: null
            PrivateKeyPath: null
            ApiTokens:
                merchant: null
                payroll: null